# Batting collapse frequency. Are England unique?

### Research Question:
- How often do batting collapses happen?
- Does England collapse more often that other teams?
- Is this statement true? "Joe Root rarely stops a collapse, and is often a part of it"
- Which players are best at stopping a collapse?


### Methodology:
- Create a table of fall of wicket:
    - MatchID
    - Date
    - Batting team
    - Bowling team
    - Match type
    - Innings
    - Fall of Wicket 1 (runs, batsman)
    - Fall of Wicket 2 (runs, batsman)
    - etc.

### Problem breakdown:
- Data Source: howstat cricket scorecards
- Extract Fall Of Wickets from a single game
- Extract FoW from multiple games
- Extract FoW from all (relevant) games

In [1]:
from cricsheet.io_html.BaseParser import BaseParser
from cricsheet.io_html.MatchParser import MatchParser

import logging
import time
import sys

In [2]:
logging.basicConfig(level=logging.DEBUG,
                    format='[%(levelname)s]: %(asctime)s: %(message)s',
                    #datefmt='%m-%d %H:%M',
                    filename='../logs/scrapeTests.log',
                    filemode='w')

# define a Handler which writes INFO messages or higher to the sys.stderr
console = logging.StreamHandler(sys.stdout)
console.setLevel(logging.INFO)

# set a format which is simpler for console use
#formatter = logging.Formatter('%(name)-12s: %(levelname)-8s: %(message)s')
formatter = logging.Formatter('[%(levelname)-8s]: %(asctime)s: %(message)s')
# tell the handler to use this format
console.setFormatter(formatter)

# add the handler to the root logger
logging.getLogger('').addHandler(console)

In [6]:
#logging.basicConfig(level=logging.INFO, format='[%(levelname)s]: %(asctime)s: %(message)s')
#log = logging.getLogger('cricsheet')

#start_time = time.time()

# 
j = 0
for i in range(1088,1089):
    j += 1
    if j % 50 == 0:
        logging.info('Sleeping for 10 seconds')
        time.sleep(10)
        
    s_id = str(i).zfill(4)
    match = MatchParser(s_id)
    logging.debug(f'Loaded match {s_id}')
    
    try:
        match.execute()
        logging.info(f'Parsed data from match {s_id}')
        match.scorecards.to_csv(f'../data/raw/csv/howstat/scorecards/scorecard_{i}.csv')
        match.fall_of_wickets.to_csv(f'../data/raw/csv/howstat/fall_of_wickets/fow_{i}.csv')
        logging.info(f'Saved data from Match: {s_id}')        
    except Exception as err:
        logging.error(err)

[INFO    ]: 2021-02-02 21:11:18,165: Parsing Match: 1088
[INFO    ]: 2021-02-02 21:11:19,252: Parsed data from match 1088
[INFO    ]: 2021-02-02 21:11:19,269: Saved data from Match: 1088

In [7]:
match.fall_of_wickets

,MatchId,MatchDate,MatchInnings,Team,TeamInnings,Wicket,Runs,Player
0,1088,1987-12-11,1,New Zealand,1st,1,0,J J Crowe
1,1088,1987-12-11,1,New Zealand,1st,2,128,Wright
2,1088,1987-12-11,1,New Zealand,1st,3,341,M D Crowe
3,1088,1987-12-11,1,New Zealand,1st,4,346,Jones
4,1088,1987-12-11,1,New Zealand,1st,5,398,Patel
5,1088,1987-12-11,1,New Zealand,1st,6,405,Gray
6,1088,1987-12-11,1,New Zealand,1st,7,473,Hadlee
7,1088,1987-12-11,1,New Zealand,1st,8,481,Bracewell
8,1088,1987-12-11,1,New Zealand,1st,9,485,Snedden
9,1088,1987-12-11,2,Australia,1st,1,29,Boon
10,1088,1987-12-11,2,Australia,1st,2,29,Jones
11,1088,1987-12-11,2,Australia,1st,3,85,Marsh
12,1088,1987-12-11,2,Australia,1st,4,201,Waugh
13,1088,1987-12-11,2,Australia,1st,5,355,Sleep
14,1088,1987-12-11,2,Australia,1st,6,380,Veletta
15,1088,1987-12-11,2,Australia,1st,7,417,Border
16,1088,1987-12-11,2,Australia,1st,8,451,McDermott
17,1088,1987-12-11,2,Australia,1st,9,489,Dyer
18,1088,1987-12-11,2,Australia,1st,10,496,Reid
19,1088,1987-12-11,3,New Zealand,2nd,1,16,Wright
20,1088,1987-12-11,3,New Zealand,2nd,2,57,J J Crowe
21,1088,1987-12-11,3,New Zealand,2nd,3,77,M D Crowe
22,1088,1987-12-11,3,New Zealand,2nd,4,139,Jones
23,1088,1987-12-11,3,New Zealand,2nd,5,153,Patel
24,1088,1987-12-11,3,New Zealand,2nd,6,170,Gray
25,1088,1987-12-11,3,New Zealand,2nd,7,179,Smith